#pragma once

#define DHT_PIN 33

#define MIN_TEMPERATURE 32
#define MAX_TEMPERATURE 36
#define ALLOWED_TEMP_CHANGE 10

#define MIN_HUMIDITY 50
#define MAX_HUMIDITY 95
#define ALLOWED_HUM_CHANGE 25

#define HX711_DATA_PIN 22
#define HX711_CLOCK_PIN 21

#define DEFAULT_SCALE_OFFSET 300000
#define DEFAULT_SCALE_CALIBRATION 115
#define ALLOWED_WEIGHT_CHANGE 2

#define SENDER_EMAIL_NAME "Beehive Monitor"
#define SENDER_EMAIL_LOGIN "EMAIL"
#define SENDER_EMAIL_PASSWORD "PASSWORD"

#define SCAN_DELAY 30

#define TIMEZONE 1
#define DAYSAVETIME 1