#pragma once
#include <EMailSender.h>

class EmailAlert {
  private:
    String _emailRecipient;
    EMailSender _emailSender;
    EMailSender::EMailMessage _message;

  public:
    EmailAlert(const char* emailLogin, const char* emailPassword, const char* senderEmail, const char* senderName);
    EmailAlert(const char* emailLogin, const char* emailPassword);
    void setEmailRecipient(String emailRecipient);
    void alertTemperatureOutOfBounds(unsigned ID, float temperature);
    void alertTemperatureChange(unsigned ID, float curTemperature, float lastTemperature);
    void alertHumidityOutOfBounds(unsigned ID, float humidity);
    void alertHumidityChange(unsigned ID, float curHumidity, float lastHumidity);
    void alertWeightChange(unsigned ID, float curWeight, float lastWeight);

  private:
    void messageFormatter(String& info, String& details, unsigned ID);
    void sendAlert();
    String getStyle();
};

EmailAlert::EmailAlert(const char* emailLogin, const char* emailPassword, const char* senderEmail, const char* senderName) 
  : _emailSender(emailLogin, emailPassword, senderEmail, senderName) {}

EmailAlert::EmailAlert(const char* emailLogin, const char* emailPassword) 
  : _emailSender(emailLogin, emailPassword) {}

void EmailAlert::setEmailRecipient(String emailRecipient) {
  _emailRecipient = emailRecipient;
}

void EmailAlert::messageFormatter(String& messageText, String& info, unsigned ID) {
  _message.message = R"(
        <html>
        <body>
            <table border="0" align="center" style="max-width: 600px; margin: 20px auto; padding: 20px; background-color: #2b2b2b; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
                <tr>
                    <td style="font-family: Arial, sans-serif;">
                        <h1 style="color: #ffeb3b; text-align: center;"> Beehive Monitor Alert</h1>
                        <br>
                        <p )" + getStyle() + R"(><strong> Alert: </strong>)" + messageText + R"(</p>
                        <p )" + getStyle() + R"(>BeeHive ID: )" + String(ID) + R"(</p>
                        )" + info + R"(<br><br>
                        <p )" + getStyle() + R"(>This email was automatically generated by Beehive Monitor. Please don't respond to this email.</p>
                    </td>
                </tr>
            </table>
        </body>
        </html>
  )";
}

void EmailAlert::alertTemperatureOutOfBounds(unsigned ID, float temperature) {
  String info = "The current temperature is out of bounds!";
  String details = "<p " + getStyle() + "><strong>Temperature: </strong>" + String(temperature) + " °C</p>";

  _message.subject = F("Alert: Temperature out of bounds!");
  messageFormatter(info, details, ID);
  sendAlert();
}

void EmailAlert::alertTemperatureChange(unsigned ID, float curTemperature, float lastTemperature) {
  String info = "There was a steep change in temperature since last reading!";
  String details = "<p>Current Temperature: " + String(curTemperature) + " °C</p>\
                    <p>Last Temperature: " + String(lastTemperature) + " °C</p>\
                    <p>Temperature Change: " + String(curTemperature - lastTemperature) + " °C</p>";

  _message.subject = F("Alert: Steep change in temperature!");
  messageFormatter(info, details, ID);
  sendAlert();
}

void EmailAlert::alertHumidityOutOfBounds(unsigned ID, float humidity) {
  String info = "The current humidity is out of bounds!";
  String details = "<p>Humidity: " + String(humidity) + "%</p>";

  _message.subject = F("Alert: Humidity out of bounds!");
  messageFormatter(info, details, ID);
  sendAlert();
}

void EmailAlert::alertHumidityChange(unsigned ID, float curHumidity, float lastHumidity) {
  String info = "There was a steep change in humidity since last reading!";
  String details = "<p>Current Humidity: " + String(curHumidity) + " °C</p>\
                    <p>Last Humidity: " + String(lastHumidity) + " °C</p>\
                    <p>Humidity Change: " + String(curHumidity - lastHumidity) + " °C</p>";

  _message.subject = F("Alert: Steep change in humidity!");
  messageFormatter(info, details, ID);
  sendAlert();
}

void EmailAlert::alertWeightChange(unsigned ID, float curWeight, float lastWeight) {
  String info = "There was a steep change in weight since last reading!";
  String details = "<p>Current Weight: " + String(curWeight) + " °C</p>\
                    <p>Last Weight: " + String(lastWeight) + " °C</p>\
                    <p>Weight Change: " + String(curWeight - lastWeight) + " °C</p>";

  _message.subject = F("Alert: Steep change in weight!");
  messageFormatter(info, details, ID);
  sendAlert();
}

void EmailAlert::sendAlert() {
  EMailSender::Response resp = _emailSender.send(_emailRecipient, _message);

  Serial.println("Sending status: ");

  Serial.println(resp.status);
  Serial.println(resp.code);
  Serial.println(resp.desc);
}

String EmailAlert::getStyle() {
  return "style=\"font-size: 16px; margin-bottom: 10px; color: #ffffff;\"";
}