#pragma once
#include <EMailSender.h>

class EmailAlert {
  private:
    String _emailRecipient;
    bool _emailSet;
    EMailSender _emailSender;
    EMailSender::EMailMessage _message;

  public:
    EmailAlert(const char* emailLogin, const char* emailPassword, const char* senderEmail, const char* senderName);
    EmailAlert(const char* emailLogin, const char* emailPassword);
    bool isEmailSet();
    void resetEmail();
    void setEmailRecipient(String emailRecipient);
    void alertTemperatureOutOfBounds(unsigned ID, float temperature);
    void alertTemperatureChange(unsigned ID, float curTemperature, float lastTemperature);
    void alertHumidityOutOfBounds(unsigned ID, float humidity);
    void alertHumidityChange(unsigned ID, float curHumidity, float lastHumidity);
    void alertWeightChange(unsigned ID, float curWeight, float lastWeight);
    void alertMultiple(unsigned ID, float curTemperature, float lastTemperature, float curHumidity, float lastHumidity, float curWeight, float lastWeight);
    void sendAlert();

  private:
    void messageFormatter(String& info, String& details, unsigned ID);
    String getStyle();
};

EmailAlert::EmailAlert(const char* emailLogin, const char* emailPassword, const char* senderEmail, const char* senderName)
  : _emailSender(emailLogin, emailPassword, senderEmail, senderName) {}

EmailAlert::EmailAlert(const char* emailLogin, const char* emailPassword)
  : _emailSender(emailLogin, emailPassword) {}

bool EmailAlert::isEmailSet() {
  return _emailSet;
}

void EmailAlert::resetEmail() {
  _emailRecipient = "";
  _emailSet = false;
}

void EmailAlert::setEmailRecipient(String emailRecipient) {
  _emailRecipient = emailRecipient;
  _emailSet = true;
}

void EmailAlert::messageFormatter(String& messageText, String& info, unsigned ID) {
  _message.message = R"(
        <html>
        <body>
            <table border="0" align="center" style="max-width: 600px; margin: 20px auto; padding: 20px; background-color: #2b2b2b; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
                <tr>
                    <td style="font-family: Arial, sans-serif;">
                        <h1 style="color: #ffeb3b; text-align: center;"> Beehive Monitor Alert</h1>
                        <br>)"
                        + getStyle() + R"(<strong> Alert: </strong>)" + messageText + R"(</p>)"
                        + getStyle() + R"(<strong> Beehive ID: </strong>)" + String(ID) + R"(</p>)"
                        + info + R"(<br><br>)"
                        + getStyle() + R"(This email was automatically generated by Beehive Monitor. Please don't respond to this email.</p>
                    </td>
                </tr>
            </table>
        </body>
        </html>
  )";
}

void EmailAlert::alertTemperatureOutOfBounds(unsigned ID, float temperature) {
  String info = "The current temperature is out of bounds!";
  String details = getStyle() + "<strong>Temperature: </strong>" + String(temperature) + "°C</p>";

  _message.subject = F("Alert: Temperature out of bounds!");
  messageFormatter(info, details, ID);
}

void EmailAlert::alertTemperatureChange(unsigned ID, float curTemperature, float lastTemperature) {
  String info = "There was a steep change in temperature since last reading!";
  String details =  getStyle() + "<strong> Current Temperature: </strong>" + String(curTemperature) + "°C</p>" +
                    getStyle() + "<strong> Last Temperature: </strong>" + String(lastTemperature) + "°C</p>" +
                    getStyle() + "<strong> Temperature Change: </strong>" + String(curTemperature - lastTemperature) + "°C</p>";

  _message.subject = F("Alert: Steep change in temperature!");
  messageFormatter(info, details, ID);
}

void EmailAlert::alertHumidityOutOfBounds(unsigned ID, float humidity) {
  String info = "The current humidity is out of bounds!";
  String details = getStyle() + "<strong>Humidity: </strong>" + String(humidity) + "%</p>";

  _message.subject = F("Alert: Humidity out of bounds!");
  messageFormatter(info, details, ID);
}

void EmailAlert::alertHumidityChange(unsigned ID, float curHumidity, float lastHumidity) {
  String info = "There was a steep change in humidity since last reading!";
  String details =  getStyle() + "<strong> Current Humidity: </strong>" + String(curHumidity) + "%</p>" +
                    getStyle() + "<strong> Last Humidity: </strong>" + String(lastHumidity) + "%</p>" +
                    getStyle() + "<strong> Humidity Change: </strong>" + String(curHumidity - lastHumidity) + "%</p>";

  _message.subject = F("Alert: Steep change in humidity!");
  messageFormatter(info, details, ID);
}

void EmailAlert::alertWeightChange(unsigned ID, float curWeight, float lastWeight) {
  String info = "There was a steep change in weight since last reading!";
  String details =  getStyle() + "<strong> Current Weight: </strong>" + String(curWeight) + "</p>" +
                    getStyle() + "<strong> Last Weight: </strong>" + String(lastWeight) + "</p>" +
                    getStyle() + "<strong> Weight Change: </strong>" + String(curWeight - lastWeight) + "</p>";

  _message.subject = F("Alert: Steep change in weight!");
  messageFormatter(info, details, ID);
}

void EmailAlert::alertMultiple(unsigned ID, float curTemperature, float lastTemperature, float curHumidity, float lastHumidity, float curWeight, float lastWeight) {
  String info = "Several values are outside the norm!";
  String details =  getStyle() + "<strong> Current Temperature: </strong>" + String(curTemperature) + "°C</p>" +
                    getStyle() + "<strong> Last Temperature: </strong>" + String(lastTemperature) + "°C</p>" +
                    getStyle() + "<strong> Temperature Change: </strong>" + String(curTemperature - lastTemperature) + "°C</p>";
                    getStyle() + "<strong> Current Humidity: </strong>" + String(curHumidity) + "%</p>" +
                    getStyle() + "<strong> Last Humidity: </strong>" + String(lastHumidity) + "%</p>" +
                    getStyle() + "<strong> Humidity Change: </strong>" + String(curHumidity - lastHumidity) + "%</p>";
                    getStyle() + "<strong> Current Weight: </strong>" + String(curWeight) + "</p>" +
                    getStyle() + "<strong> Last Weight: </strong>" + String(lastWeight) + "</p>" +
                    getStyle() + "<strong> Weight Change: </strong>" + String(curWeight - lastWeight) + "</p>";

  _message.subject = F("Alert: Multiple values out of the norm!");
  messageFormatter(info, details, ID);
}

void EmailAlert::sendAlert() {
  if (_emailRecipient != "") {
    EMailSender::Response resp = _emailSender.send(_emailRecipient, _message);
    Serial.println("Sending status: ");
    Serial.println(resp.desc);
  }
}

String EmailAlert::getStyle() {
  return "<p style=\"font-size: 16px; margin-bottom: 10px; color: #ffffff;\">";
}